# Form implementation generated from reading ui file 'calculate.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qfluentwidgets import BodyLabel, CaptionLabel, ComboBox, LineEdit, PrimaryPushButton, RadioButton, TextEdit, TitleLabel
from PyQt6 import QtCore, QtGui, QtWidgets
from json import loads

translation = {}
try:
    with open("translation.json", "r", encoding="utf-8") as f:
        translation = loads(f.read())
except FileNotFoundError:
    raise FileNotFoundError("../translation.json not found!")


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 500)
        Form.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.TitleLabel = TitleLabel(parent=Form)
        self.TitleLabel.setGeometry(QtCore.QRect(80, 10, 145, 38))
        self.TitleLabel.setObjectName("TitleLabel")
        self.layoutWidget = QtWidgets.QWidget(parent=Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 90, 254, 369))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel = BodyLabel(parent=self.layoutWidget)
        self.BodyLabel.setProperty("pixelFontSize", 16)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout.addWidget(self.BodyLabel)
        self.LineEdit = LineEdit(parent=self.layoutWidget)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_2 = BodyLabel(parent=self.layoutWidget)
        self.BodyLabel_2.setProperty("pixelFontSize", 16)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_2.addWidget(self.BodyLabel_2)
        self.LineEdit_2 = LineEdit(parent=self.layoutWidget)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.horizontalLayout_2.addWidget(self.LineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.BodyLabel_3 = BodyLabel(parent=self.layoutWidget)
        self.BodyLabel_3.setProperty("pixelFontSize", 18)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.verticalLayout.addWidget(self.BodyLabel_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RadioButton = RadioButton(parent=self.layoutWidget)
        self.RadioButton.setObjectName("RadioButton")
        self.horizontalLayout_3.addWidget(self.RadioButton)
        self.RadioButton_2 = RadioButton(parent=self.layoutWidget)
        self.RadioButton_2.setObjectName("RadioButton_2")
        self.horizontalLayout_3.addWidget(self.RadioButton_2)
        self.RadioButton_3 = RadioButton(parent=self.layoutWidget)
        self.RadioButton_3.setObjectName("RadioButton_3")
        self.horizontalLayout_3.addWidget(self.RadioButton_3)
        self.RadioButton_4 = RadioButton(parent=self.layoutWidget)
        self.RadioButton_4.setObjectName("RadioButton_4")
        self.horizontalLayout_3.addWidget(self.RadioButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.resregion = CaptionLabel(parent=self.layoutWidget)
        self.resregion.setProperty("pixelFontSize", 17)
        self.resregion.setObjectName("resregion")
        self.verticalLayout_2.addWidget(self.resregion)
        self.TextEdit = TextEdit(parent=self.layoutWidget)
        self.TextEdit.setObjectName("TextEdit")
        self.verticalLayout_2.addWidget(self.TextEdit)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.PrimaryPushButton = PrimaryPushButton(parent=self.layoutWidget)
        self.PrimaryPushButton.setObjectName("PillPushButton")
        self.verticalLayout_2.addWidget(self.PrimaryPushButton)
        self.language = ComboBox(parent=Form)
        self.language.setGeometry(QtCore.QRect(20, 50, 91, 33))
        self.language.setObjectName("language")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "简易计算器"))
        self.TitleLabel.setText(_translate("Form", "简易计算器"))
        self.BodyLabel.setText(_translate("Form", "输入第一个数字"))
        self.BodyLabel_2.setText(_translate("Form", "输入第二个数字"))
        self.BodyLabel_3.setText(_translate("Form", "请选择运算方式:"))
        self.RadioButton.setText(_translate("Form", "加"))
        self.RadioButton_2.setText(_translate("Form", "减"))
        self.RadioButton_3.setText(_translate("Form", "乘"))
        self.RadioButton_4.setText(_translate("Form", "除"))
        self.resregion.setText(_translate("Form", "输出区域："))
        self.PrimaryPushButton.setText(_translate("Form", "开始运算"))

    def change_language(self, index):
        global translation
        lang = "cn"
        if index == 0:
            lang = "cn"
        elif index == 1:
            lang = "en"
        self.TitleLabel.move(30, 5)
        self.TitleLabel.setFixedWidth(320)
        self.TitleLabel.setText(translation["Form"]["简易计算器"][lang])
        self.BodyLabel.setText(translation["Form"]["输入第一个数字"][lang])
        self.BodyLabel_2.setText(translation["Form"]["输入第二个数字"][lang])
        self.BodyLabel_3.setText(translation["Form"]["请选择运算方式:"][lang])
        self.RadioButton.setText(translation["Form"]["加"][lang])
        self.RadioButton_2.setText(translation["Form"]["减"][lang])
        self.RadioButton_3.setText(translation["Form"]["乘"][lang])
        self.RadioButton_4.setText(translation["Form"]["除"][lang])
        self.resregion.setText(translation["Form"]["输出区域："][lang])
        self.PrimaryPushButton.setText(translation["Form"]["开始运算"][lang])
