# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_cardWin(object):
    def setupUi(self, cardWin):
        cardWin.setObjectName("cardWin")
        cardWin.resize(500, 350)
        self.TitleLabel = TitleLabel(parent=cardWin)
        self.TitleLabel.setGeometry(QtCore.QRect(180, 20, 124, 38))
        self.TitleLabel.setObjectName("TitleLabel")
        self.widget = QtWidgets.QWidget(parent=cardWin)
        self.widget.setGeometry(QtCore.QRect(110, 80, 230, 104))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel = BodyLabel(parent=self.widget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout.addWidget(self.BodyLabel)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.LineEdit = LineEdit(parent=self.widget)
        self.LineEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.LineEdit.setFont(font)
        self.LineEdit.setText("")
        self.LineEdit.setDragEnabled(False)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_2 = BodyLabel(parent=self.widget)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout_2.addWidget(self.BodyLabel_2)
        spacerItem2 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.LineEdit_2 = LineEdit(parent=self.widget)
        self.LineEdit_2.setFrame(True)
        self.LineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.horizontalLayout_2.addWidget(self.LineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(cardWin)
        QtCore.QMetaObject.connectSlotsByName(cardWin)

    def retranslateUi(self, cardWin):
        _translate = QtCore.QCoreApplication.translate
        cardWin.setWindowTitle(_translate("cardWin", "Qt Designer ui"))
        self.TitleLabel.setText(_translate("cardWin", "登录界面"))
        self.BodyLabel.setText(_translate("cardWin", "用户名"))
        self.LineEdit.setPlaceholderText(_translate("cardWin", "请输入用户名"))
        self.BodyLabel_2.setText(_translate("cardWin", "密码"))
        self.LineEdit_2.setPlaceholderText(_translate("cardWin", "请输入密码"))
from qfluentwidgets import BodyLabel, CardWidget, LineEdit, TitleLabel
