# Form implementation generated from reading ui file 'datepicker.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qfluentwidgets import AMTimePicker, CalendarPicker, DatePicker, TimePicker, ZhDatePicker
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Date(object):
    def setupUi(self, Date):
        Date.setObjectName("Date")
        Date.resize(415, 377)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Date)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=Date)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CalendarPicker = CalendarPicker(parent=Date)
        self.CalendarPicker.setObjectName("CalendarPicker")
        self.horizontalLayout.addWidget(self.CalendarPicker)
        self.DatePicker = DatePicker(parent=Date)
        self.DatePicker.setObjectName("DatePicker")
        self.horizontalLayout.addWidget(self.DatePicker)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ZhDatePicker = ZhDatePicker(parent=Date)
        self.ZhDatePicker.setObjectName("ZhDatePicker")
        self.horizontalLayout_2.addWidget(self.ZhDatePicker)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.TimePicker = TimePicker(parent=Date)
        self.TimePicker.setObjectName("TimePicker")
        self.verticalLayout.addWidget(self.TimePicker)
        self.AMTimePicker = AMTimePicker(parent=Date)
        self.AMTimePicker.setObjectName("AMTimePicker")
        self.verticalLayout.addWidget(self.AMTimePicker)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Date)
        QtCore.QMetaObject.connectSlotsByName(Date)

    def retranslateUi(self, Date):
        _translate = QtCore.QCoreApplication.translate
        Date.setWindowTitle(_translate("Date", "Date"))
