# Form implementation generated from reading ui file 'DbDemo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qfluentwidgets import LineEdit, PlainTextEdit, PushButton, StrongBodyLabel
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ui_Db(object):
    def setupUi(self, ui_Db):
        ui_Db.setObjectName("ui_Db")
        ui_Db.resize(501, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(ui_Db)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.StrongBodyLabel_3 = StrongBodyLabel(parent=ui_Db)
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.horizontalLayout_4.addWidget(self.StrongBodyLabel_3)
        self.usernameEdit = LineEdit(parent=ui_Db)
        self.usernameEdit.setObjectName("usernameEdit")
        self.horizontalLayout_4.addWidget(self.usernameEdit)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(
            80, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.StrongBodyLabel_4 = StrongBodyLabel(parent=ui_Db)
        self.StrongBodyLabel_4.setObjectName("StrongBodyLabel_4")
        self.horizontalLayout_5.addWidget(self.StrongBodyLabel_4)
        self.passwordEdit = LineEdit(parent=ui_Db)
        self.passwordEdit.setObjectName("passwordEdit")
        self.horizontalLayout_5.addWidget(self.passwordEdit)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StrongBodyLabel_2 = StrongBodyLabel(parent=ui_Db)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.horizontalLayout.addWidget(self.StrongBodyLabel_2)
        spacerItem2 = QtWidgets.QSpacerItem(
            32, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.HostEdit = LineEdit(parent=ui_Db)
        self.HostEdit.setObjectName("HostEdit")
        self.horizontalLayout.addWidget(self.HostEdit)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.StrongBodyLabel = StrongBodyLabel(parent=ui_Db)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.horizontalLayout_2.addWidget(self.StrongBodyLabel)
        self.DbNameEdit = LineEdit(parent=ui_Db)
        self.DbNameEdit.setObjectName("DbNameEdit")
        self.horizontalLayout_2.addWidget(self.DbNameEdit)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.PlainTextEdit = PlainTextEdit(parent=ui_Db)
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.horizontalLayout_10.addWidget(self.PlainTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.createBtn = PushButton(parent=ui_Db)
        self.createBtn.setObjectName("createBtn")
        self.horizontalLayout_3.addWidget(self.createBtn)
        self.conBtn = PushButton(parent=ui_Db)
        self.conBtn.setObjectName("conBtn")
        self.horizontalLayout_3.addWidget(self.conBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label = QtWidgets.QLabel(parent=ui_Db)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.passwordEdit.setEchoMode(self.passwordEdit.EchoMode.Password)
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(ui_Db)
        QtCore.QMetaObject.connectSlotsByName(ui_Db)

    def retranslateUi(self, ui_Db):
        _translate = QtCore.QCoreApplication.translate
        ui_Db.setWindowTitle(_translate("ui_Db", "DbDemo"))
        self.StrongBodyLabel_3.setText(_translate("ui_Db", "Username"))
        self.StrongBodyLabel_4.setText(_translate("ui_Db", "password"))
        self.StrongBodyLabel_2.setText(_translate("ui_Db", "Host"))
        self.StrongBodyLabel.setText(_translate("ui_Db", "Database Name"))
        self.createBtn.setText(_translate("ui_Db", "创建数据库"))
        self.conBtn.setText(_translate("ui_Db", "连接"))
