# Form implementation generated from reading ui file 'loginPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(600, 400)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(login)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ImageLabel = ImageLabel(parent=login)
        self.ImageLabel.setObjectName("ImageLabel")
        self.verticalLayout_2.addWidget(self.ImageLabel)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.PixmapLabel = PixmapLabel(parent=login)
        self.PixmapLabel.setObjectName("PixmapLabel")
        self.horizontalLayout_4.addWidget(self.PixmapLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleLabel = TitleLabel(parent=login)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.StrongBodyLabel = StrongBodyLabel(parent=login)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.horizontalLayout_2.addWidget(self.StrongBodyLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.LineEdit_2 = LineEdit(parent=login)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.horizontalLayout_2.addWidget(self.LineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StrongBodyLabel_2 = StrongBodyLabel(parent=login)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.horizontalLayout.addWidget(self.StrongBodyLabel_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.LineEdit = LineEdit(parent=login)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SwitchButton = SwitchButton(parent=login)
        self.SwitchButton.setObjectName("SwitchButton")
        self.horizontalLayout_3.addWidget(self.SwitchButton)
        self.PrimaryPushButton = PrimaryPushButton(parent=login)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.horizontalLayout_3.addWidget(self.PrimaryPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "登录页"))
        self.TitleLabel.setText(_translate("login", "登录页"))
        self.StrongBodyLabel.setText(_translate("login", "账户"))
        self.StrongBodyLabel_2.setText(_translate("login", "密码"))
        self.SwitchButton.setOnText(_translate("login", "登录"))
        self.SwitchButton.setOffText(_translate("login", "注册"))
        self.PrimaryPushButton.setText(_translate("login", "登录"))
from qfluentwidgets import ImageLabel, LineEdit, PixmapLabel, PrimaryPushButton, StrongBodyLabel, SwitchButton, TitleLabel
