# Form implementation generated from reading ui file 'showInfo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qfluentwidgets import TableWidget
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_table(object):
    def setupUi(self, table):
        table.setObjectName("table")
        table.resize(400, 305)
        self.verticalLayout = QtWidgets.QVBoxLayout(table)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TableWidget = TableWidget(parent=table)
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.TableWidget)

        self.retranslateUi(table)
        QtCore.QMetaObject.connectSlotsByName(table)

    def retranslateUi(self, table):
        _translate = QtCore.QCoreApplication.translate
        table.setWindowTitle(_translate("table", "信息展示页"))
