# Form implementation generated from reading ui file 'VChange.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_changeTool(object):
    def setupUi(self, changeTool):
        changeTool.setObjectName("changeTool")
        changeTool.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(changeTool)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleLabel = TitleLabel(parent=changeTool)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StrongBodyLabel = StrongBodyLabel(parent=changeTool)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.horizontalLayout.addWidget(self.StrongBodyLabel)
        self.LineEdit = LineEdit(parent=changeTool)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)
        self.PushButton = PushButton(parent=changeTool)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.StrongBodyLabel_2 = StrongBodyLabel(parent=changeTool)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.horizontalLayout_2.addWidget(self.StrongBodyLabel_2)
        self.LineEdit_2 = LineEdit(parent=changeTool)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.horizontalLayout_2.addWidget(self.LineEdit_2)
        self.PushButton_2 = PushButton(parent=changeTool)
        self.PushButton_2.setObjectName("PushButton_2")
        self.horizontalLayout_2.addWidget(self.PushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.TextEdit = TextEdit(parent=changeTool)
        self.TextEdit.setObjectName("TextEdit")
        self.verticalLayout.addWidget(self.TextEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formatSelect = EditableComboBox(parent=changeTool)
        self.formatSelect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formatSelect.sizePolicy().hasHeightForWidth())
        self.formatSelect.setSizePolicy(sizePolicy)
        self.formatSelect.setObjectName("formatSelect")
        self.horizontalLayout_3.addWidget(self.formatSelect)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.PrimaryPushButton = PrimaryPushButton(parent=changeTool)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.horizontalLayout_3.addWidget(self.PrimaryPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.SwitchButton = SwitchButton(parent=changeTool)
        self.SwitchButton.setObjectName("SwitchButton")
        self.horizontalLayout_3.addWidget(self.SwitchButton)
        self.ToolButton = ToolButton(parent=changeTool)
        self.ToolButton.setObjectName("ToolButton")
        self.horizontalLayout_3.addWidget(self.ToolButton)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(changeTool)
        QtCore.QMetaObject.connectSlotsByName(changeTool)

    def retranslateUi(self, changeTool):
        _translate = QtCore.QCoreApplication.translate
        changeTool.setWindowTitle(_translate("changeTool", "VChange"))
        self.TitleLabel.setText(_translate("changeTool", "图片视频转换器"))
        self.StrongBodyLabel.setText(_translate("changeTool", "输入文件"))
        self.PushButton.setText(_translate("changeTool", "选择输入文件"))
        self.StrongBodyLabel_2.setText(_translate("changeTool", "输出文件"))
        self.PushButton_2.setText(_translate("changeTool", "选择输出路径"))
        self.PrimaryPushButton.setText(_translate("changeTool", "开始转换"))
        self.SwitchButton.setText(_translate("changeTool", "图片"))
        self.SwitchButton.setOnText(_translate("changeTool", "视频"))
        self.SwitchButton.setOffText(_translate("changeTool", "图片"))
from qfluentwidgets import EditableComboBox, LineEdit, PrimaryPushButton, PushButton, StrongBodyLabel, SwitchButton, TextEdit, TitleLabel, ToolButton
